Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
casefolding_abstrak = data['Abstrak'].str.lower()
casefolding_label = data['Kategori'].str.lower()
data_casefolding = pd.DataFrame(casefolding_abstrak)
data_casefolding
------------------


[0;31m[0m
[0;31mNameError[0mTraceback (most recent call last)
[0;32m<ipython-input-4-52fe14104913>[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m [0mcasefolding_abstrak[0m [0;34m=[0m [0mdata[0m[0;34m[[0m[0;34m'Abstrak'[0m[0;34m][0m[0;34m.[0m[0mstr[0m[0;34m.[0m[0mlower[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mcasefolding_label[0m [0;34m=[0m [0mdata[0m[0;34m[[0m[0;34m'Kategori'[0m[0;34m][0m[0;34m.[0m[0mstr[0m[0;34m.[0m[0mlower[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mdata_casefolding[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mDataFrame[0m[0;34m([0m[0mcasefolding_abstrak[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mdata_casefolding[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'data' is not defined

